**Aim: To purchase items from the existing 30 items in inventory**

**1)Reading the record.json file**

In [1]:
import json

fd = open("record.json",'r')
r = fd.read()
fd.close()

records = json.loads(r)

In [2]:
records

{'1001': {'cat': 'food item',
  'name': 'Choco Cake',
  'pr': 100,
  'qn': 34,
  'wt': '500 grams'},
 '1002': {'cat': 'food item',
  'name': 'Milk Cake',
  'pr': 800,
  'qn': 100,
  'wt': '200 grams'},
 '1003': {'cat': 'food item',
  'name': 'Drink',
  'pr': 85,
  'qn': 100,
  'wt': '100 grams'},
 '1004': {'cat': 'food item',
  'name': 'Candy',
  'pr': 5,
  'qn': 1000,
  'wt': '5 grams'},
 '1005': {'cat': 'Study material',
  'name': 'Pen',
  'pr': 20,
  'qn': 100,
  'wt': '500 grams'},
 '1006': {'cat': 'Electronics',
  'name': 'Phone',
  'pr': 50000,
  'qn': 10,
  'wt': '500 grams'},
 '1007': {'cat': 'Electronics',
  'name': 'Mic',
  'pr': 1500,
  'qn': 0,
  'wt': '500 grams'},
 '1008': {'cat': 'Electronics',
  'name': 'Case',
  'pr': 599,
  'qn': 5,
  'wt': '500 grams'},
 '1009': {'cat': 'Electronics',
  'name': 'Keyboard',
  'pr': 1999,
  'qn': 10,
  'wt': '500 grams'},
 '1010': {'cat': 'Food Items',
  'name': 'Soup',
  'pr': 30,
  'qn': 90,
  'wt': '100 grams'},
 '1011': {'cat': 'fo

**2)Purchasing 2 phones(1006)**

In [3]:
ui_prod  = str(input("Enter the product_Id: "))
ui_quant = int(input("Enter the quantity: "))


print("Product: ", records[ui_prod]['name'])
print("Price: ", records[ui_prod]['pr'])
print("Billing Amount: ", records[ui_prod]['pr'] * ui_quant)

records[ui_prod]['qn'] = records[ui_prod]['qn'] - ui_quant

Enter the product_Id: 1006
Enter the quantity: 2
Product:  Phone
Price:  50000
Billing Amount:  100000


**2.1)Dumping the purchased quantities of phone**

In [4]:
js = json.dumps(records)

fd = open("record.json",'w')
fd.write(js)
fd.close()

In [5]:
{'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant}

{'amount': 100000, 'prod': '1006', 'qn': 2}

In [6]:
sales = {1 : {'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant},
         2 : {'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant},
         3 : {'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant}}

In [7]:
sale = json.dumps(sales)

In [8]:
sale

'{"1": {"prod": "1006", "qn": 2, "amount": 100000}, "2": {"prod": "1006", "qn": 2, "amount": 100000}, "3": {"prod": "1006", "qn": 2, "amount": 100000}}'

**2.2)Showing the updated quantity of item 1006.(From 10 to 8)**

In [9]:
records


{'1001': {'cat': 'food item',
  'name': 'Choco Cake',
  'pr': 100,
  'qn': 34,
  'wt': '500 grams'},
 '1002': {'cat': 'food item',
  'name': 'Milk Cake',
  'pr': 800,
  'qn': 100,
  'wt': '200 grams'},
 '1003': {'cat': 'food item',
  'name': 'Drink',
  'pr': 85,
  'qn': 100,
  'wt': '100 grams'},
 '1004': {'cat': 'food item',
  'name': 'Candy',
  'pr': 5,
  'qn': 1000,
  'wt': '5 grams'},
 '1005': {'cat': 'Study material',
  'name': 'Pen',
  'pr': 20,
  'qn': 100,
  'wt': '500 grams'},
 '1006': {'cat': 'Electronics',
  'name': 'Phone',
  'pr': 50000,
  'qn': 8,
  'wt': '500 grams'},
 '1007': {'cat': 'Electronics',
  'name': 'Mic',
  'pr': 1500,
  'qn': 0,
  'wt': '500 grams'},
 '1008': {'cat': 'Electronics',
  'name': 'Case',
  'pr': 599,
  'qn': 5,
  'wt': '500 grams'},
 '1009': {'cat': 'Electronics',
  'name': 'Keyboard',
  'pr': 1999,
  'qn': 10,
  'wt': '500 grams'},
 '1010': {'cat': 'Food Items',
  'name': 'Soup',
  'pr': 30,
  'qn': 90,
  'wt': '100 grams'},
 '1011': {'cat': 'foo

**3)Purchasing item 1029 (Banana Bread).Quantity 2**

In [10]:
ui_prod  = str(input("Enter the product_Id: "))
ui_quant = int(input("Enter the quantity: "))


print("Product: ", records[ui_prod]['name'])
print("Price: ", records[ui_prod]['pr'])
print("Billing Amount: ", records[ui_prod]['pr'] * ui_quant)

records[ui_prod]['qn'] = records[ui_prod]['qn'] - ui_quant

Enter the product_Id: 1029
Enter the quantity: 2
Product:  Banana Bread
Price:  40
Billing Amount:  80


In [11]:
js = json.dumps(records)

fd = open("record.json",'w')
fd.write(js)
fd.close()

In [12]:
{'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant}

{'amount': 80, 'prod': '1029', 'qn': 2}

In [13]:
sales = {1 : {'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant},
         2 : {'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant},
         3 : {'prod' : ui_prod, 'qn' : ui_quant, 'amount': records[ui_prod]['pr'] * ui_quant}}

**3.1)Upadating the new quantity of banana bread afer purchase**

In [14]:
sale = json.dumps(sales)

In [15]:
sale

'{"1": {"prod": "1029", "qn": 2, "amount": 80}, "2": {"prod": "1029", "qn": 2, "amount": 80}, "3": {"prod": "1029", "qn": 2, "amount": 80}}'

**3)Showing the updated quantity of item 1029 from 500 to 498**

In [16]:
records

{'1001': {'cat': 'food item',
  'name': 'Choco Cake',
  'pr': 100,
  'qn': 34,
  'wt': '500 grams'},
 '1002': {'cat': 'food item',
  'name': 'Milk Cake',
  'pr': 800,
  'qn': 100,
  'wt': '200 grams'},
 '1003': {'cat': 'food item',
  'name': 'Drink',
  'pr': 85,
  'qn': 100,
  'wt': '100 grams'},
 '1004': {'cat': 'food item',
  'name': 'Candy',
  'pr': 5,
  'qn': 1000,
  'wt': '5 grams'},
 '1005': {'cat': 'Study material',
  'name': 'Pen',
  'pr': 20,
  'qn': 100,
  'wt': '500 grams'},
 '1006': {'cat': 'Electronics',
  'name': 'Phone',
  'pr': 50000,
  'qn': 8,
  'wt': '500 grams'},
 '1007': {'cat': 'Electronics',
  'name': 'Mic',
  'pr': 1500,
  'qn': 0,
  'wt': '500 grams'},
 '1008': {'cat': 'Electronics',
  'name': 'Case',
  'pr': 599,
  'qn': 5,
  'wt': '500 grams'},
 '1009': {'cat': 'Electronics',
  'name': 'Keyboard',
  'pr': 1999,
  'qn': 10,
  'wt': '500 grams'},
 '1010': {'cat': 'Food Items',
  'name': 'Soup',
  'pr': 30,
  'qn': 90,
  'wt': '100 grams'},
 '1011': {'cat': 'foo